# Flask settings
HOST = 'localhost'
PORT = 5000
STATIC_URL_PATH = '/'
STATIC_FOLDER = 'static'
MODELS_FOLDER = 'models'
DEBUG_ACTIVE = True

# Device ID
deviceID = {
    'CLIENT': 'N96JPTRJUDTMIOBXJUSV',
    'VR-HEADSET': '8NAM2FGQ77U6IHW8ULXX',
    'SYSTEM': '4UINYUTCHGH06GJ3XFBJ'
}

# Database settings
DB_NAME = 'database.db'
MODEL_ID_LENTGH = 32
MODEL_NAME_MAX_LENTGH = 100
TEXTURE_ID_LENGTH = 32
REQUESTER_ID_MAX_LENGTH = 100